version: '3'

volumes:

  pg_data:
  static:
  media:

services:

  db:
    build: ./backend/
    container_name: kittygram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: rerolll/kittygram_backend
    container_name: kittygram_backend
    env_file: .env
    volumes:
      - media:/media/
      - static:/backend_static
    depends_on:
      - db

  frontend:
    build: ./frontend/
    container_name: kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    build: ./nginx/
    container_name: kittygram_gateway
    env_file: .env
    volumes:
      - media:/media/
      - static:/staticfiles/
    ports:
      - 9000:80
